baseURL = "http://www.mryagni.com"
languageCode = "en-us"
title = "Mr. Yagni's Site"
theme = 'ananke'

[params]
    author = "Mr. Yagni"
    description = "A site dedicated to the YAGNI software development principle"

[menu]
    [[menu.main]]
        name = "About Me"
        url = "/bio/"
        weight = 3
